# appveyor.yml for Windows
build: off

clone_folder: c:\gopath\src\github.com\iwdgo\testingfiles

environment:
  GOPATH: c:\gopath

stack: go 1.12

before_test:
  - go vet ./...
  - mkdir output

test_script:
  - go test -cover -race ./...
