language: go

go:
  - 1.11.x
  - tip

before_install:
  - go get -t -v ./...
  - go vet ./...
  - mkdir output

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)