name: Go
on: [push]
jobs:

  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Complete Go set up
        shell: bash
        run: |
          mkdir -p $(go env GOCACHE)
          mkdir -p $(go env GOMODCACHE)
          mkdir -p $(dirname $(go env GOENV))
          mkdir -p $(go env GOPATH)/bin
          echo $PATH

      - name: Vet
        run: go vet

      - name: Install
        run: go install

      - name: Test
        run: |
          mkdir output
          go test -cover -race
